config/routes.rb
Phlickr::Application.routes.draw do
  root to: "static_pages#root"

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :photos, only: :create

  namespace :api do
    resources :photos, only: [:new]
  end

  namespace :api, defaults: { format: :json } do
    get "users/profile", to: "users#profile"
    # get "photos/explore", to: "photos#explore"
    get "photos/explore/:page_num", to: "photos#explore"
    get "photos/favorites", to: "photos#favorites"
    get "photos/change_favorite", to: "photos#change_favorite"
    resources :users, only: [:show]
    resources :users, only: [] do
      resources :photos, only: [:index]
    end
    resources :photos, except: [:new, :edit, :index]
    resources :albums, except: [:new, :edit]
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :integer          not null, primary key
#  username         :string(255)      not null
#  password_digest  :string(255)      not null
#  session_token    :string(255)      not null
#  created_at       :datetime
#  updated_at       :datetime
#  fname            :string(255)
#  lname            :string(255)
#  profile_photo_id :integer
#

class User < ActiveRecord::Base
  attr_reader :password
  validates :username, :password_digest, presence: true
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true, :uniqueness => true
  validates :username, uniqueness: true

  before_validation :ensure_session_token, :ensure_profile_photo

  has_many :photos
  has_many :albums
  has_many :favorite_photos
  has_many :favorited_photos, through: :favorite_photos, source: :photo
  belongs_to :profile_photo,
    class_name: "Photo",
    foreign_key: :profile_photo_id,
    primary_key: :id

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user.try(:is_password?, password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def password=(unencrypted_password)
    if unencrypted_password.present?
      @password = unencrypted_password
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def is_password?(unencrypted_password)
    BCrypt::Password.new(self.password_digest).is_password?(unencrypted_password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def ensure_profile_photo
    if self.profile_photo_id == nil
      self.profile_photo_id = 24 # TODO: fix this
      # self.profile_photo = Photo.find_by(description: "Default Profile Picture").id
    end
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController

  def profile
    @user = current_user
    @photos = current_user.photos
    render partial: "api/users/profile", locals: { user: @user }
  end

  def show
    @user = User.find(params[:id])
    render json: @user
  end  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      session[:has_toured] = false
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new, status: 422
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="container auth-page">
  <div class="row auth-row">
    <div class='col-xs-offset-5'>

      <div class="row">
        <form role="form" class="col-xs-3"
          action="<%= users_url %>" method="POST">
          <%= auth_token_input %>
          <div class="form-group">
            <label>
              Username<br>
              <input id="username" type="text" class="form-control" name="user[username]">
            </label>
          </div>
          <div class="form-group">
            <label>
              Password<br>
              <input id="password" class="form-control" type="password" name="user[password]">
            </label>
          </div>
          <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Sign Up">
            <a class="link-other-login" href="<%= new_session_url %>">Back to Login</a>
          </div>
        </form>
      </div>

      <div class="row">
        <form role="form"
          class="col-xs-3"
          action="<%= session_url %>"
          method="post">
          <%= auth_token_input %>
          <input type="hidden"
            name="guest"
            value="true">
          <div class="form-group">
            <input type="submit"
              class="btn btn-lg btn-primary"
              value="Use Guest Account">
          </div>
        </form>
      </div>

    </div>
  </div>
</div>